Fix instantiation in `_to_rekor()` for optional inclusion promise (#1382)
* betterproto: avoid assigning a var of type Optional[InclusionPromise] to TransparencyLogEntry.inclusion_promise

```
  File "/usr/local/google/home/rpetgrave/src/ssp/sigstore-python/sigstore/models.py", line 262, in _to_rekor
    tlog_entry = rekor_v1.TransparencyLogEntry(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/rpetgrave/src/ssp/.venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 120, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TransparencyLogEntry
inclusion_promise
  Input should be a dictionary or an instance of InclusionPromise [type=dataclass_type, input_value=None, input_type=NoneType]
```

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* add test

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* Revert "betterproto: avoid assigning a var of type Optional[InclusionPromise] to TransparencyLogEntry.inclusion_promise"

This reverts commit 46b0087f616faa1a194242e9892ac8856c53bc2c.

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* cleanup

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* Reapply "betterproto: avoid assigning a var of type Optional[InclusionPromise] to TransparencyLogEntry.inclusion_promise"

This reverts commit 43dc46895414bdd6a053c6a93a9d389c776c2a47.

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* cleanup

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* format

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* also delete integrated_time

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* lint

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

* remove mention of pydantic in changelog

Signed-off-by: Ramon Petgrave <32398091+ramonpetgrave64@users.noreply.github.com>

---------

Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>
Signed-off-by: Ramon Petgrave <32398091+ramonpetgrave64@users.noreply.github.com>
Co-authored-by: Jussi Kukkonen <jkukkonen@google.com>